### ISSUE TITLE
Examples in Mechanics/Mechanics_IO out of date

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#101]
A number of examples in examples/Mechanics/Mechanics_IO/ are out of date.

**Comment by radarsat1** [comment]
Que pasa Vincent :)

~~~
sinclairs@bicycle:~/projects/siconos/examples/Mechanics/MechanicsIO (master)
$ python cylinder.py | grep mechanics_io
Traceback (most recent call last):
  File "cylinder.py", line 9, in <module>
    from mechanics_io import Hdf5
ImportError: No module named mechanics_io

sinclairs@bicycle:~/projects/siconos/examples/Mechanics/MechanicsIO (master)
$ python cylinder.py 
Traceback (most recent call last):
  File "cylinder.py", line 9, in <module>
    from mechanics_io import Hdf5
ImportError: No module named mechanics_io

sinclairs@bicycle:~/projects/siconos/examples/Mechanics/MechanicsIO (master)
$ git blame cylinder.py | grep mechanics_io
796f2b84 (Vincent Acary    2016-12-11 16:16:57 +0100  9) from mechanics_io import Hdf5

sinclairs@bicycle:~/projects/siconos/examples/Mechanics/MechanicsIO (master)
$ git show 796f2b84 | grep mechanics_io
-from siconos.io.mechanics_io import Hdf5
+from mechanics_io import Hdf5
~~~

It's ok, I continue to look at the other problems.. ;P

**Comment by radarsat1** [comment]
I should mention that I did not test the occ examples as I do not have occ enabled in my build right now.
