### ISSUE TITLE
siconos_mechanisms is no longer working

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#123]
siconos_mechanisms throws an exception
`Exception: Runtime Exception : Topology::indexSet: indexSet does not exist`

~~~
----- ~/siconos/examples/Mechanics/Mechanisms/SliderCrank -----                                                      [11:31:43][0]
[acary@ohana]$ siconos_mechanisms 
##################################################################
############## Siconos/Mechanics mechanisms module ###############
##################################################################
############## Enrironment variable                ###############
sys.executable:  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
sys.path:  ['/Users/acary/.local/bin', '/Users/acary/Library/Python/2.7/lib/python/site-packages/network_viz-0.1-py2.7.egg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/swiglpk-1.0.0-py2.7-macosx-10.11-x86_64.egg', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/network_viz-0.1-py2.7.egg', '/Users/acary/siconos/examples/Mechanics/Mechanisms/SliderCrank', '/Users/acary/Library/Python/2.7/lib/python2.7/site-packages', '/Users/acary/.local.old/lib/python2.7/site-packages', '/Users/acary/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/Users/acary/Work/NonsmoothModes/siconos/OscillatorChains/tools-python', '/scratch/Vincent/Build/gmsh/wrappers', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/readline', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/acary/Library/Python/2.7/lib/python/site-packages', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/Users/acary/Library/Python/2.7/lib/python2.7/site-packages']
############## Loading of definition files         ###############
siconos-mechanisms.py, info: mbtbLocalOptions.py loaded
siconos-mechanisms.py, info: ./bodydef.py  loaded
Using PyQt4
 ###### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
Graphic_Driver created.
Cocoa window created.
V3d_Viewer created.
V3d_View created
AIS_InteractiveContext created.
Display3d class successfully initialized.
 ########################################
././CAD/chamber.step
CADMBTB_loadCADFile id = 3 using file ././CAD/contact_b_cyl.step.
      ...    Step File Reading : ././CAD/contact_b_cyl.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 0.000216 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 0.000403 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
   253 records (entities,sub-lists,scopes), 614 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 0.000624 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 0.000922 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
  STEP Loading done : 150 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=2.
CADMBTB_loadCADFile 3 affected, type=1.
CADMBTB_loadCADFile id = 4 using file ././CAD/chamber.step.
      ...    Step File Reading : ././CAD/chamber.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 0.000183 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 0.000359 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
   253 records (entities,sub-lists,scopes), 614 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 0.000575 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 0.000901 Seconds 
CPU user time: 0 seconds 
CPU system time: 0 seconds 
  STEP Loading done : 150 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=2.
CADMBTB_loadCADFile 4 affected, type=1.
CADMBTB_initContact id =0,type1=1,type2=1.
MBTB_LOAD_CONTACT UVBOUNDS idContact1=0,U1=3.141593e+00,U2=6.283185e+00,V1=-1.000000e-03,V2=0.000000e+00
MBTB_LOAD_CONTACT UVBOUNDS idContact2=0,U1=3.141593e+00,U2=6.283185e+00,V1=-6.000000e-01,V2=0.000000e+00
MBTB_Contact::setInteraction(SP::Interaction newInteraction)
_interaction before0x0
newinteraction 0x7fae36978bf0
======= Interaction display number 0 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
_interaction after0x7fae36978bf0
======= Interaction display number 0 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
././CAD/chamber.step
CADMBTB_loadCADFile id = 5 using file ././CAD/contact_h_cyl.step.
      ...    Step File Reading : ././CAD/contact_h_cyl.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.650000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 3.420000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   253 records (entities,sub-lists,scopes), 614 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 6.160000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 8.820000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 150 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=2.
CADMBTB_loadCADFile 5 affected, type=1.
CADMBTB_loadCADFile id = 6 using file ././CAD/chamber.step.
      ...    Step File Reading : ././CAD/chamber.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.620000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 3.270000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   253 records (entities,sub-lists,scopes), 614 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 5.320000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 8.600000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 150 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=2.
CADMBTB_loadCADFile 6 affected, type=1.
CADMBTB_initContact id =1,type1=1,type2=1.
MBTB_LOAD_CONTACT UVBOUNDS idContact1=1,U1=3.141593e+00,U2=6.283185e+00,V1=-1.000000e-03,V2=0.000000e+00
MBTB_LOAD_CONTACT UVBOUNDS idContact2=1,U1=3.141593e+00,U2=6.283185e+00,V1=-6.000000e-01,V2=0.000000e+00
MBTB_Contact::setInteraction(SP::Interaction newInteraction)
_interaction before0x0
newinteraction 0x7fae36974850
======= Interaction display number 1 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
_interaction after0x7fae36974850
======= Interaction display number 1 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
././CAD/AxisBody2.stp
CADMBTB_loadCADFile id = 7 using file ././CAD/RingBody1.stp.
      ...    Step File Reading : ././CAD/RingBody1.stp
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.190000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 2.430000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   151 records (entities,sub-lists,scopes), 356 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 4.019999999999e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 5.899999999999e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 86 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=1.
CADMBTB_loadCADFile 7 affected, type=1.
CADMBTB_loadCADFile id = 8 using file ././CAD/AxisBody2.stp.
      ...    Step File Reading : ././CAD/AxisBody2.stp
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 5.900000000003e-05 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 1.210000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   62 records (entities,sub-lists,scopes), 134 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 2.090000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 3.250000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 28 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=0.
CADMBTB_loadCADFile 8 affected, type=2.
CADMBTB_initContact id =2,type1=1,type2=2.
MBTB_LOAD_CONTACT UVBOUNDS idContact1=2,U1=0.000000e+00,U2=6.283185e+00,V1=0.000000e+00,V2=1.000000e-02
MBTB_LOAD_CONTACT UVBOUNDS idContact2=2,U1=0.000000e+00,U2=4.000000e-02,V1=0.000000e+00,V2=0.000000e+00
MBTB_Contact::setInteraction(SP::Interaction newInteraction)
_interaction before0x0
newinteraction 0x7fae36997d90
======= Interaction display number 2 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
_interaction after0x7fae36997d90
======= Interaction display number 2 =======
| lowerLevelForOutput : 0
| upperLevelForOutput : 1
| lowerLevelForInput : 0
| upperLevelForInput : 1
| interactionSize : 3
| _sizeOfDS : 0
| =====> Relation of type 2 and subtype 0
| y[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| yOld[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| y_k[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[0] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
| lambda[1] : [3](0.000000e+00,0.000000e+00,0.000000e+00)
===================================
User plugin :  SliderCrankPlugin.so
CADMBTB_loadCADFile id = 0 using file ././CAD/body1.step.
      ...    Step File Reading : ././CAD/body1.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.430000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 2.870000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   202 records (entities,sub-lists,scopes), 481 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 4.650000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 6.760000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 118 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=3.
CADMBTB_loadCADFile 0 affected, type=1.
Warning : NewtonEulerDS::setBoundaryConditions. old boundary conditions were pre-existing
CADMBTB_loadCADFile id = 1 using file ././CAD/body2.step.
      ...    Step File Reading : ././CAD/body2.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.450000000000e-04 Seconds 
CPU user time: 1.000000000000e-02 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 2.899999999999e-04 Seconds 
CPU user time: 1.000000000000e-02 seconds 
CPU system time: 0.000000000000e+00 seconds 
   202 records (entities,sub-lists,scopes), 481 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 4.719999999999e-04 Seconds 
CPU user time: 1.000000000000e-02 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 7.180000000000e-04 Seconds 
CPU user time: 1.000000000000e-02 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 118 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=3.
CADMBTB_loadCADFile 1 affected, type=1.
CADMBTB_loadCADFile id = 2 using file ././CAD/Slider.step.
      ...    Step File Reading : ././CAD/Slider.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.360000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 2.730000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   253 records (entities,sub-lists,scopes), 614 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 4.679999999999e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 6.989999999999e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 150 Entities
importSTEP Solid, nb shapes: 1CADMBTB_loadCADFile number of face=2.
CADMBTB_loadCADFile 2 affected, type=1.
run.py, info: joint points not defined.
CADMBTB_loadArtefactCADFile using file ././CAD/artefact2.step.
      ...    Step File Reading : ././CAD/artefact2.step
      ...    STEP File   Read    ... 
Elapsed time: 0 Hours 0 Minutes 1.200000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ... Step File loaded  ... 
Elapsed time: 0 Hours 0 Minutes 2.250000000000e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
   151 records (entities,sub-lists,scopes), 356 parameters

      ... Parameters prepared ... Elapsed time: 0 Hours 0 Minutes 3.960000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
      ...   Objets analysed  ... 
Elapsed time: 0 Hours 0 Minutes 6.060000000001e-04 Seconds 
CPU user time: 0.000000000000e+00 seconds 
CPU system time: 0.000000000000e+00 seconds 
  STEP Loading done : 86 Entities
importSTEP Solid, nb shapes: 1
====> Initialisation ...

Traceback (most recent call last):
  File "/Users/acary/.local/bin/siconos_mechanisms", line 180, in <module>
    mbtb.MBTB_initSimu(stepSize, withProj)
  File "/Users/acary/Library/Python/2.7/lib/python2.7/site-packages/siconos/mechanics/mechanisms/mbtb.py", line 375, in MBTB_initSimu
    return _mbtb.MBTB_initSimu(hTS, withProj)
Exception: Runtime Exception : Topology::indexSet: indexSet does not exist
----- ~/siconos/examples/Mechanics/Mechanisms/SliderCrank -----                                                      [11:31:47][1]
[acary@ohana]$ 
~~~

**Comment by vacary** [comment]
Fix with 2b1914685814c594c7ba1a28437c7c513a806350

The number of index sets was wrong. All the examples using MoreauJeanCombinedProjectionOSI drew not working anymore.
