### ISSUE TITLE
Unicode in comments causes problems with swig-generated Python

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#149]
I just found that in the Docker setup that I use for verifying my Siconos build, compiling for Python 2 produces .py files that lead to the error,

~~~
root@5a1b74afc7bb:~/build/wrap# python -c 'import siconos.kernel as sk; print sk.__file__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "siconos/kernel.py", line 33879
SyntaxError: Non-ASCII character '\xe2' in file siconos/kernel.py on line 33880, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
~~~

It only seems to be an issue with this Docker container based on 14.04, which has the following software versions:

~~~
swig3.0 -version: SWIG Version 3.0.2
gcc --version: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
python --version: Python 2.7.6
~~~

It doesn't appear to be a problem on my 16.04 laptop, which has Python 2.7.12.  Oddly I can't find the error on c-dash.. However, it's such an easy fix I think it would be a shame to leave this before 4.1.

One way to fix it would be to remove all the accents and such from our files, but it would be better to just specify the file encoding.  All that is needed is to prepend the following to every .py file generated by swig:

    # -*- coding: utf-8 -*-

Unfortunately I haven't been able to figure out how to get swig to do this.  I tried adding the following to `start.i`:

~~~
%pythonbegin %{
# -*- coding: utf-8 -*-
%}
~~~

But this unfortunately places the comment after the "This file was generated by SWIG..." comment block.  It *must* be in the first 2 lines of the file for Python to recognize it.  We could do it using CMake I guess, but I hesitate..

~~~
find . -name \*.py -exec sed -i 's/\(# This file was automatically generated\)/# -*- coding: utf-8 -*-\n\1/' {} \;
~~~

In any case, after some searching I haven't found a way to get SWIG to do this directly.

**Comment by radarsat1** [comment]
Went with the last solution, executing a bit of shell script as a post-build step for .i files.  I hope it doesn't break anything, please report any issues.
