### ISSUE TITLE
[mechanics_io] time_of_birth broken for MoreauJeanDirectProjectionOSI

### ISSUE THREAD

**Issue by radarsat1** [siconos/siconos#150]
Probably just need to ensure the `_M` matrix is correctly sized in LinearOSNS, i.e., probably just need to reset `_hasBeenUpdated` at the right moment.

output:

~~~
step 502 < 2001
Traceback (most recent call last):
  File "cylindrical_stops.py", line 139, in <module>
    osi=Kernel.MoreauJeanDirectProjectionOSI,
  File "/home/sinclairs/.local/lib/python2.7/site-packages/siconos/io/mechanics_io.py", line 2544, in run
    log(simulation.computeOneStep, with_timer)()
  File "/home/sinclairs/.local/lib/python2.7/site-packages/siconos/io/mechanics_io.py", line 233, in silent
    fun(*args)
  File "/home/sinclairs/.local/lib/python2.7/site-packages/siconos/kernel.py", line 24270, in computeOneStep
    return _kernel.TimeStepping_computeOneStep(self)
Exception: Siconos Matrix Exception : SimpleMatrix::setBlock(row,col): row is out of range
~~~

relevant gdb backtrace:
~~~
#2  0x00007ffff1fcdf53 in SimpleMatrix::setBlock (this=0x14c5a20, row_min=0, col_min=0, m
=...) at /home/sinclairs/projects/siconos/kernel/src/utils/SiconosAlgebra/SimpleMatrixSet
Get.cpp:107
#3  0x00007ffff23ed31c in OSNSMatrixProjectOnConstraints::fill (this=0x14c59d0, indexSet=
..., update=false) at /home/sinclairs/projects/siconos/kernel/src/simulationTools/OSNSMat
rixProjectOnConstraints.cpp:140
#4  0x00007ffff23ebf32 in LinearOSNS::preCompute (this=0x12c5360, time=5.0200000000000005
) at /home/sinclairs/projects/siconos/kernel/src/simulationTools/LinearOSNS.cpp:739
#5  0x00007ffff23de810 in MLCP::preCompute (this=0x12c5360, time=5.0200000000000005) at /
home/sinclairs/projects/siconos/kernel/src/simulationTools/MLCP.cpp:142
#6  0x00007ffff23de881 in MLCP::compute (this=0x12c5360, time=5.0200000000000005) at /hom
e/sinclairs/projects/siconos/kernel/src/simulationTools/MLCP.cpp:153
#7  0x00007ffff2351ceb in Simulation::computeOneStepNSProblem (this=0x12c5bc0, Id=1) at /
home/sinclairs/projects/siconos/kernel/src/simulationTools/Simulation.cpp:356
#8  0x00007ffff2327633 in TimeSteppingDirectProjection::advanceToEvent (this=0x12c5bc0) a
t /home/sinclairs/projects/siconos/kernel/src/simulationTools/TimeSteppingDirectProjectio
n.cpp:209
#9  0x00007ffff23982d5 in TimeStepping::computeOneStep (this=0x12c5bc0) at /home/sinclair
s/projects/siconos/kernel/src/simulationTools/TimeStepping.cpp:363
~~~

**Comment by radarsat1** [comment]
I've been unable to reproduce this recently, even with slightly older versions. I'll close this, unless I stumble on it again and can make a repeatable test.
