### ISSUE TITLE
Music_run_py fails due to missing file

### ISSUE THREAD

**Issue by xhub** [siconos/siconos#177]
Traceback (most recent call last):
  File "/builds/workspace/continuous3/examples/Mechanics/Music/run.py", line 52, in <module>
    frets_positions = scipy.io.loadmat(frets_file)['h'][:600, 0]
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 134, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 57, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: './donnees_siconos/pb2_h.mat'

**Comment by vacary** [comment]
I do not understand since the data are on the git repo since 8 days.
