### ISSUE TITLE
issue with new siconos_vview in python3 after merge #227

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#229]
Following the merge of #227 , I have a problem with siconos_vview in python3. I suppose that the problem comes python3.

Do you experience the same problem ?

```
siconos__vview cube.hdf5
Cube
Ground
Traceback (most recent call last):
  File "/Users/acary/.local/bin/siconos_vview", line 20, in <module>
    vview.run()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1937, in run
    self.initialize_vtk()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1923, in initialize_vtk
    self.setup_initial_position()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1588, in setup_initial_position
    self.set_dynamic_actors_visibility(self.time0)
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1482, in set_dynamic_actors_visibility
    self.set_visibility_v(self.dynamic_actors.keys(), time)
  File "/Users/acary/Library/Python/3.5/lib/python/site-packages/numpy/lib/function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/acary/Library/Python/3.5/lib/python/site-packages/numpy/lib/function_base.py", line 2804, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/Users/acary/Library/Python/3.5/lib/python/site-packages/numpy/lib/function_base.py", line 2764, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1459, in set_dynamic_instance_visibility
    tob = self.times_of_birth.get(instance, -1)
TypeError: unhashable type: 'dict_keys'
```

**Comment by radarsat1** [comment]
I have not tested with Python3 due to lack of support for VTK on Linux.  I'll see if I can fix it.  Thanks for pointing it out.

**Comment by radarsat1** [comment]
Can you try the fix I just pushed?  If there are many more python3 issues I'll try harder to install VTK for Python3.

**Comment by vacary** [comment]
It is fixed. Perfect. Many thanks
