### ISSUE TITLE
siconos_vview do not longer work with mesh file.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#285]
```
----- ~/siconos-tutorials/examples/mechanics/GeometricPrimitives -----                                                      [22:05:10][0]
[acary@ohana-2]$ siconos_vview mesh.hdf5 
/Users/acary/Library/Python/3.5/lib/python/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Warning: Error loading configuration `/Users/acary/.config/siconos_vview.json'
/usr/local/lib/python3.5/site-packages/vtk/util/numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \
Generic Warning: In /Users/acary/Softs/VTK-8.1.2/Common/Core/vtkInstantiator.cxx, line 265
vtkInstantiator::CreateInstance was deprecated for VTK 8.1 and will be removed in a future version.

Generic Warning: In /Users/acary/Softs/VTK-8.1.2/Rendering/Core/vtkMapper.cxx, line 186
vtkMapper::ImmediateModeRenderingOff was deprecated for VTK 8.1 and will be removed in a future version.

Traceback (most recent call last):
  File "/Users/acary/.local/bin/siconos_vview", line 23, in <module>
    vview.run()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 2363, in run
    self.initialize_vtk()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 2322, in initialize_vtk
    self.init_instances()
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1715, in init_instances
    self.init_instance(instance_name)
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1711, in init_instance
    self.init_contactor(contactor_instance_name, instance,  instid)
  File "/Users/acary/Library/Python/3.5/lib/python3.5/site-packages/siconos/io/vview.py", line 1642, in init_contactor
    if not (self.global_filter or self.opts.export):
AttributeError: 'VView' object has no attribute 'global_filter'
```

**Comment by vacary** [comment]
fixed in 54f793b707aa6c6c51fdb5ea02c9c53e0cc6f9a7
