### ISSUE TITLE
How to postprocess a hdf5 file produced by siconos/Mechanics ?

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#316]

**Comment by vacary** [comment]
There are mainly two ways to postprocess an hdf5 file produced by a simulation with siconos_numerics

1 - Using `siconos_vview`, it is possible to get a simple VTK rendering
``` siconos_vview foo.hdf5```
there are plenty of options `to siconos_vview`
``` siconos_vview --help```

2 - Using `siconos_vexport`, to produce for instance vtk files for paraview
``` siconos_vexport --global-filter foo.hdf5```
In case be used in parallel for large simulations files.

**Comment by ali145** [comment]
Hi,
I try to visualize the results of an example in vtk format but I have these error messages:

perhaps, I don't know how convert hdf5 files to vtk!

thanks


========================================
/examples/mechanics/RigidBodiesCollection$ siconos_vview n_cubes.hdf5
ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x17dbd10): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 854, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 12)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x1ec3400): Algorithm vtkPythonAlgorithm(0x17dbd10) returned failure for request: vtkInformation (0x1f414f0)
  Debug: Off
  Modified Time: 8421
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x17dbd10): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 854, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 777, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/ginger/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 213, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 12)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x1ec3400): Algorithm vtkPythonAlgorithm(0x17dbd10) returned failure for request: vtkInformation (0x1f414f0)
  Debug: Off
  Modified Time: 31315
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



Traceback (most recent call last):
  File "/usr/local/bin/siconos_vview", line 23, in <module>
    vview.run()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2695, in run
    self.initialize_vtk()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2663, in initialize_vtk
    self.setup_initial_position()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2102, in setup_initial_position
    self.pos_t0 = [self.io_reader.pos_data]
AttributeError: 'IOReader' object has no attribute 'pos_data'

**Comment by vacary** [comment]
This issue  is related to #359  

Are you using h5py 3.0.0?

**Comment by ali145** [comment]
Yes,

Just I wanted to visualize a model in vtk (paraview) for that I tried "siconos_vview" for an output file in format hdf5, I had above error message (for a standard example of siconos).

how can I find a document explaining the structure of input data (for example geometry generation) and also output file (for example in vtk over time steps)?


Merci
