### ISSUE TITLE
siconos_vview problem (h5py 3.0.0)

### ISSUE THREAD

**Issue by franckbourrier** [siconos/siconos#359]
Hi,

I installed the latest siconos and it seems there is a problem with siconos_vview and vexport. It is related with vtk (I have vtk7 installed). 

Thank you for your help 

Here is a copy from the terminal ....
------------------------------
```
ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x1e22120): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 845, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/franck/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 774, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/franck/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 210, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 200)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x252eda0): Algorithm vtkPythonAlgorithm(0x1e22120) returned failure for request: vtkInformation (0x2626e20)
  Debug: Off
  Modified Time: 8458
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Filters/Python/vtkPythonAlgorithm.cxx, line 191
vtkPythonAlgorithm (0x1e22120): Failure when calling method: "ProcessRequest": 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 151, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
  File "/usr/lib/python3/dist-packages/vtk/util/vtkAlgorithm.py", line 197, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 845, in RequestData
    self.pos_data = self._idpos_data[self._id_t_m, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/franck/.local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 774, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/franck/.local/lib/python3.6/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 210, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 200)
.

ERROR: In /build/vtk7-w4DzBd/vtk7-7.1.1+dfsg1/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkCompositeDataPipeline (0x252eda0): Algorithm vtkPythonAlgorithm(0x1e22120) returned failure for request: vtkInformation (0x2626e20)
  Debug: Off
  Modified Time: 2970853
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
  FORWARD_DIRECTION: 0



Traceback (most recent call last):
  File "/usr/local/bin/siconos_vview", line 23, in <module>
    vview.run()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2685, in run
    self.initialize_vtk()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2654, in initialize_vtk
    self.setup_initial_position()
  File "/usr/local/lib/python3.6/dist-packages/siconos/io/vview.py", line 2093, in setup_initial_position
    self.pos_t0 = [self.io_reader.pos_data]
AttributeError: 'IOReader' object has no attribute 'pos_data'
```
--------------------------------

**Comment by vacary** [comment]
Are you sure that there are some trajectory in your hdf5 file ? siconos_vview is not able to work with any simulation step.

Could you also  try with 807b6d1 ? charts are no longer working with recent version of vtk

**Comment by franckbourrier** [comment]
I tried with  807b6d1 and the error remains. I am sure there are several steps and also several bodies (I also have the same error with the examples from siconos-tutorials).

**Comment by vacary** [comment]
Could you attach your hdf5 file such that I tried in my installation with vtk8 ?

**Comment by franckbourrier** [comment]
This one (among others) generates the problem 
[2d_primitives.zip](https://github.com/siconos/siconos/files/5487721/2d_primitives.zip)

**Comment by vacary** [comment]
No problem on my side with vtk8. 
I will try to downgrade to 7.1.1.

**Comment by vacary** [comment]
The problem seems come from h5py no ?

**Comment by vacary** [comment]
In the meanwhile, you can use the tsk output for paraview 
```
  siconos_vexport --global-filter 2d_primitives.hdf5 
```

**Comment by franckbourrier** [comment]
siconos_vexport does not work neither -> same error
it doesn't come from vtk because I upgraded to 8.1.2

**Comment by franckbourrier** [comment]
you were right, it was a h5py issue in 3.0.0 (released 5 days ago). I downgraded to 2.10.0.

**Comment by vacary** [comment]
Cool. 
Thank you for the feedback that might help other users.

**Comment by drew-parsons** [comment]
Not sure why this issue was closed. As far as I can see the failure with h5py 3.0 is still in place.  Was there a commit which fixed the problem?

**Comment by radarsat1** [comment]
It so happens that I fixed this last night in the debian package, it is not even available yet but I will push the change upstream to siconos as well.  See [this patch](https://salsa.debian.org/science-team/siconos/-/blob/master/debian/patches/fix-filter-indexing-bug.patch)  Maybe something similar is needed for vexport.

**Comment by vacary** [comment]
@radarsat1 Many thanks

**Comment by drew-parsons** [comment]
Great, thanks @radarsat1
