### ISSUE TITLE
Type problem in mechanics_run. All examples broken.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#397]
An issue has been raised with some last recent commits

```
[acary@ohana]$ python cube.py 
[io.mechanics] setup model simulation ...
[io.mechanics] 
[io.mechanics] Simulation will run from time 0.0000 to 10.0000s, step 1 to step 20001 (h=0.0005, times=[?,?])
[io.mechanics] 
[io.mechanics] import scene ...
[io.mechanics] import dynamical systems ...
[io.mechanics] Import  dynamic or static object number  1 from initial state
[io.mechanics]                 object name    cube
[io.mechanics] Import  dynamic or static object number  1 from initial state
[io.mechanics]                 object name    cube
Traceback (most recent call last):
  File "/Users/acary/siconos-tutorials/examples/mechanics/GeometricPrimitives/cube.py", line 64, in <module>
    io.run(with_timer=False,
  File "/Users/acary/Library/Python/3.9/lib/python3.9/site-packages/siconos/io/mechanics_run.py", line 2333, in run
    self.import_scene(t0, body_class, shape_class, face_class, edge_class)
  File "/Users/acary/Library/Python/3.9/lib/python3.9/site-packages/siconos/io/mechanics_run.py", line 1649, in import_scene
    self.import_object(name=name, body_class=body_class,
  File "/Users/acary/Library/Python/3.9/lib/python3.9/site-packages/siconos/io/mechanics_run.py", line 1535, in import_object
    body = self.import_bullet_object(
  File "/Users/acary/Library/Python/3.9/lib/python3.9/site-packages/siconos/io/mechanics_run.py", line 1106, in import_bullet_object
    body.setNumber(number)
  File "/Users/acary/Library/Python/3.9/lib/python3.9/site-packages/siconos/kernel.py", line 2762, in setNumber
    return _kernel.DynamicalSystem_setNumber(self, new_number)
TypeError: in method 'DynamicalSystem_setNumber', argument 2 of type 'size_t'
```

**Comment by vacary** [comment]
The modification in 6e81d56fb22c4b96fcfe2084ab95b9cbca56e60e to fix conversion problems raises issues in swig.

The problem seems come fom an unknown type in swig. This is discussed in the documentation here http://www.swig.org/Doc1.3/SWIG.html
Should add this line or come back to int or unsigned int type ?

**Comment by fperignon** [comment]
I think it's better to try the typedef for size_t or the %import "sys/types.h"
(and I thought it was done ?). I'll have a look to this.

**Comment by vacary** [comment]
we have only that in the kernel.i:
```
// a std::size_t definition (otherwise swig complains about it)
namespace std
{
  typedef size_t size_t;
}
```

**Comment by fperignon** [comment]
yes, maybe the namespace is not considered or misunderstood in swig.
We should probably add somewhere in .i files
typedef unsigned int size_t
