### ISSUE TITLE
Add a time of birth and boundary conditions in the same time

### ISSUE THREAD

**Issue by hetierm** [siconos/siconos#406]
Hi everyone,

I am trying to add some boundaries conditions to an object which does not exist at the beginning of the simulation, and I have some difficulties.

Typically, the scene is :

    io.add_primitive_shape('Ground', 'Box2d', (10, 1),
                           insideMargin=0.0, outsideMargin=0)
    io.add_primitive_shape('Sphere', 'Disk', (1,),
                           insideMargin=0.0, outsideMargin=0)

    io.add_object('ground_load', [Contactor('Ground')], translation=[0,0])

    io.add_object('sphere_load', [Contactor('Sphere')], translation=[0,5], mass=1, inertia=0.1, time_of_birth=1)
    io.add_boundary_condition('fixed_x', 'sphere_load', indices=[0,2], bc_class='FixedBC')

and I got the following error :
  Traceback (most recent call last):
    File "load.py", line 53, in <module>
      io.run(verbose=True,
    File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 2372, in run
      self.import_scene(t0, body_class, shape_class, face_class, edge_class)
    File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 1694, in import_scene
      self.import_boundary_conditions(name)
    File "/usr/local/lib/python3.8/dist-packages/siconos/io/mechanics_run.py", line 1362, in import_boundary_conditions
      ds1 = topo.getDynamicalSystem(ds1_name)
    File "/usr/local/lib/python3.8/dist-packages/siconos/kernel.py", line 3150, in getDynamicalSystem
      return _kernel.Topology_getDynamicalSystem(self, *args)
  Exception: std::exception

I think that is due to the fact that boundaries conditions are load at the beginning of the computation, while the object (called sphere_load in my case) is only created at time t=1. So, is there any way to add a time of birth for boundaries conditions ?

**Comment by vacary** [comment]
Marc,

Could you send us a minimal testing example ?

**Comment by hetierm** [comment]
Here it is :

from siconos.mechanics.collision.tools import Contactor
from siconos.io.mechanics_run import MechanicsHdf5Runner
from siconos.mechanics.collision.bullet import SiconosBulletOptions

import siconos.numerics as sn
import siconos.kernel as sk


# Creation of the hdf5 file for input/output
with MechanicsHdf5Runner() as io:
    
    wall_x = 8
    width = 1

    io.add_primitive_shape('Ground', 'Box2d', (10*wall_x, width),
                           insideMargin=0.0, outsideMargin=0)
    io.add_primitive_shape('Sphere', 'Disk', (1,),
                           insideMargin=0.0, outsideMargin=0)


    io.add_object('ground_load', [Contactor('Ground')], translation=[0,0])

    # io.add_object('sphere_load', [Contactor('Sphere')], translation=[0,5], mass=1, inertia=0.1)
    io.add_object('sphere_load', [Contactor('Sphere')], translation=[0,5], mass=1, inertia=0.1, time_of_birth=1)

    io.add_boundary_condition('fixed_x', 'sphere_load', indices=[2], bc_class='FixedBC')

    io.add_Newton_impact_friction_nsl('contact', mu=0.1, e=1)


bullet_options = SiconosBulletOptions()
bullet_options.worldScale = 1.0
bullet_options.contactBreakingThreshold = 0.04
bullet_options.dimension = 1
bullet_options.perturbationIterations = 0
bullet_options.minimumPointsPerturbationThreshold = 0

options = sk.solver_options_create(sn.SICONOS_FRICTION_2D_NSGS)
options.iparam[sn.SICONOS_IPARAM_MAX_ITER] = 100
options.dparam[sn.SICONOS_DPARAM_TOL] = 1e-4


with MechanicsHdf5Runner(mode='r+') as io:
    io.run(verbose=True,
        with_timer=False,
        bullet_options=bullet_options,
        face_class=None,
        edge_class=None,
        t0=0,
        T=2,
        h=0.001,
        theta=0.50001,
        Newton_max_iter=1,
        set_external_forces=None,
        solver_options=options,
        numerics_verbose=False,
        output_frequency=None)

**Comment by hetierm** [comment]
Here it is :
[testing_example.zip](https://github.com/siconos/siconos/files/6570767/testing_example.zip)
