### ISSUE TITLE
siconos_vview crashes with occ backend and mechanisms component.

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#489]
siconos_vview crashes with occ backend when trying to view `siconos_mechanisms.hdf5`

A first issue raises if there is no static object in the simulation:
```
----- ~/siconos-tutorials/examples/mechanics/Mechanisms/SliderCrank ----- (git:master)                                                      [21:16:49][0]
[vincent@ohana-2]$ siconos_vview siconos_mechanisms.hdf5 
[io.vview] Loaded configuration from  /Users/vincent/.config/siconos_vview.json
[io.vview]    background_color :  [0.2, 0.2, 0.2]
[io.vview]    window_size :  [2526, 1692]
[io.vview]    static_bodies_color :  [1.0, 0.0, 0.0]
[io.vview]    dynamic_bodies_color :  [0.0, 0.0, 1.0]
2024-01-16 21:17:07.032 (   1.081s) [         235676B] vtkPythonAlgorithm.cxx:112    ERR| vtkPythonAlgorithm (0x6000014a00b0): Failure when calling method: "ProcessRequest":
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/vtkmodules/util/vtkAlgorithm.py", line 152, in ProcessRequest
    return vtkself.ProcessRequest(request, inInfo, outInfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vtkmodules/util/vtkAlgorithm.py", line 198, in ProcessRequest
    return self.RequestData(request, inInfo, outInfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/vview.py", line 985, in RequestData
    self._static_id_t_m = [self._static_indices[static_id_t]]
                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```
this can be easily circumvented by taking into account that there is no static object with an `if` in the script.

On the other hand, the script literally crashes when you try to mesh from the .step file stored in the hdf5 file. For the record, it works like a charm when I try to execute the same procedure on an independent .step file

**Comment by vacary** [comment]
fix by #490
This was an encoding problem when reading step content in hdf5
