### ISSUE TITLE
siconos_vview crashes due to "OSError: [Errno 24] Too many open files"

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#491]
The command `siconos_vview siconos_mechanisms.hdf5 ` in ` siconos-tutorials/examples/mechanics/Mechanisms/Trip_Magnetic`
 crashes. The context manager `tmpfile` does not close the file

```
Traceback (most recent call last):
  File "/Users/vincent/.local/bin/siconos_vview", line 23, in <module>
    vview.run()
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/vview.py", line 2997, in run
    self.initialize_vtk()
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/vview.py", line 2953, in initialize_vtk
    self.init_shapes()
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/vview.py", line 1915, in init_shapes
    self.init_shape(shape_name)
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/vview.py", line 1704, in init_shape
    reader = topods_shape_reader(e)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/mechanics_hdf5.py", line 438, in topods_shape_reader
    print( "get_open_fds() is: ", get_open_fds() )
                                  ^^^^^^^^^^^^^^
  File "/Users/vincent/.local/lib/python3.11/site-packages/siconos/io/mechanics_hdf5.py", line 413, in get_open_fds
    raw_procs = subprocess.check_output(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1849, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
                                  ^^^^^^^^^
OSError: [Errno 24] Too many open files
```

**Comment by vacary** [comment]
fix with [e9eec95](https://github.com/siconos/siconos/pull/490/commits/e9eec955ddbddfccdb4eda19d58a66c353d62a8f)
