### ISSUE TITLE
occ backend is no longer produced with last cmake config and OpenCASCADE 7.4.0

### ISSUE THREAD

**Issue by vacary** [siconos/siconos#494]
```
[vincent@ohana-2]$ python occ_watch_escapement.py
No module named siconos.fclib.
Traceback (most recent call last):
  File "/Users/vincent/siconos-tutorials/examples/mechanics/MultiBodySystems/WatchEscapment/occ_watch_escapement.py", line 20, in <module>
    siconos.io.mechanics_run.set_backend('occ')
  File "/Users/vincent/.virtualenvs/siconos/lib/python3.11/site-packages/siconos/io/mechanics_run.py", line 94, in set_backend
    setup_default_classes()
  File "/Users/vincent/.virtualenvs/siconos/lib/python3.11/site-packages/siconos/io/mechanics_run.py", line 140, in setup_default_classes
    default_simulation_class = occ.OccTimeStepping
                               ^^^
NameError: name 'occ' is not defined. Did you mean: 'oct'?

```

**Comment by vacary** [comment]
Finally, A solution has been found?

**Comment by bremond** [comment]
With #499, compilation with OpenCascade 7.6 ok (probably ok with 7.4 also). Issues in vview with occ_slider_crank and pythonocc 7.6 + vtk 9. occ_bouncing_ball.py : the ball is falling through the ground.
